/* --- Generated the 12/3/2020 at 16:9 --- */
/* --- heptagon compiler, version 1.03.00 (compiled thu. may. 3 2:35:29 CET 2018) --- */
/* --- Command line: /usr/local/bin/heptc -target c greenhouse_controller.ept --- */

#ifndef GREENHOUSE_CONTROLLER_H
#define GREENHOUSE_CONTROLLER_H

#include "greenhouse_controller_types.h"
typedef struct Greenhouse_controller__greenhouse_controller_greenhouse_c2_out {
  int greenhouse_c2;
} Greenhouse_controller__greenhouse_controller_greenhouse_c2_out;

void Greenhouse_controller__greenhouse_controller_greenhouse_c2_step(
int greenhouse_v_281, int greenhouse_v_282, int greenhouse_v_285,
int greenhouse_v_286, int greenhouse_v_289, int greenhouse_v_290,
int greenhouse_v_293, int greenhouse_v_294, int greenhouse_v_295,
int greenhouse_v_300, int greenhouse_v_301, int greenhouse_v_303,
int greenhouse_v_304, int greenhouse_v_306, int greenhouse_v_307,
int greenhouse_v_309, int greenhouse_v_310, int greenhouse_v_317,
int greenhouse_v_322, int greenhouse_v_328, int greenhouse_v_334,
int greenhouse_v_340, int greenhouse_v_346, int greenhouse_v_352,
int greenhouse_v_354, int greenhouse_v_359, int greenhouse_v_361,
int greenhouse_v_367, int greenhouse_v_369, int greenhouse_v_375,
int greenhouse_v_377, int greenhouse_v_383, int greenhouse_v_385,
int greenhouse_v_391, int greenhouse_v_393, int greenhouse_v_401,
int greenhouse_v_406, int greenhouse_v_412, int greenhouse_v_418,
int greenhouse_v_424, int greenhouse_v_430, int greenhouse_v_436,
int greenhouse_v_438, int greenhouse_v_443, int greenhouse_v_445,
int greenhouse_v_451, int greenhouse_v_453, int greenhouse_v_459,
int greenhouse_v_461, int greenhouse_v_467, int greenhouse_v_469,
int greenhouse_v_475, int greenhouse_v_477, int greenhouse_v_485,
int greenhouse_v_490, int greenhouse_v_496, int greenhouse_v_502,
int greenhouse_v_508, int greenhouse_v_514, int greenhouse_v_520,
int greenhouse_v_525, int greenhouse_v_531, int greenhouse_v_537,
int greenhouse_v_543, int greenhouse_v_549, int greenhouse_ck_1,
int greenhouse_pnr_4, int greenhouse_ck_7_1, int greenhouse_pnr_3,
int greenhouse_v_643, int greenhouse_v_642, int greenhouse_pnr_2,
int greenhouse_v_627, int greenhouse_v_626, int greenhouse_pnr_1,
int greenhouse_v_611, int greenhouse_v_610, int greenhouse_pnr,
int p_greenhouse_c2, int p_greenhouse_c1, int greenhouse_c1,
Greenhouse_controller__greenhouse_controller_greenhouse_c2_out* _out);

typedef struct Greenhouse_controller__greenhouse_controller_greenhouse_c1_out {
  int greenhouse_c1;
} Greenhouse_controller__greenhouse_controller_greenhouse_c1_out;

void Greenhouse_controller__greenhouse_controller_greenhouse_c1_step(
int greenhouse_v_281, int greenhouse_v_282, int greenhouse_v_285,
int greenhouse_v_286, int greenhouse_v_289, int greenhouse_v_290,
int greenhouse_v_293, int greenhouse_v_294, int greenhouse_v_295,
int greenhouse_v_300, int greenhouse_v_301, int greenhouse_v_303,
int greenhouse_v_304, int greenhouse_v_306, int greenhouse_v_307,
int greenhouse_v_309, int greenhouse_v_310, int greenhouse_v_317,
int greenhouse_v_322, int greenhouse_v_328, int greenhouse_v_334,
int greenhouse_v_340, int greenhouse_v_346, int greenhouse_v_352,
int greenhouse_v_354, int greenhouse_v_359, int greenhouse_v_361,
int greenhouse_v_367, int greenhouse_v_369, int greenhouse_v_375,
int greenhouse_v_377, int greenhouse_v_383, int greenhouse_v_385,
int greenhouse_v_391, int greenhouse_v_393, int greenhouse_v_401,
int greenhouse_v_406, int greenhouse_v_412, int greenhouse_v_418,
int greenhouse_v_424, int greenhouse_v_430, int greenhouse_v_436,
int greenhouse_v_438, int greenhouse_v_443, int greenhouse_v_445,
int greenhouse_v_451, int greenhouse_v_453, int greenhouse_v_459,
int greenhouse_v_461, int greenhouse_v_467, int greenhouse_v_469,
int greenhouse_v_475, int greenhouse_v_477, int greenhouse_v_485,
int greenhouse_v_490, int greenhouse_v_496, int greenhouse_v_502,
int greenhouse_v_508, int greenhouse_v_514, int greenhouse_v_520,
int greenhouse_v_525, int greenhouse_v_531, int greenhouse_v_537,
int greenhouse_v_543, int greenhouse_v_549, int greenhouse_ck_1,
int greenhouse_pnr_4, int greenhouse_ck_7_1, int greenhouse_pnr_3,
int greenhouse_v_643, int greenhouse_v_642, int greenhouse_pnr_2,
int greenhouse_v_627, int greenhouse_v_626, int greenhouse_pnr_1,
int greenhouse_v_611, int greenhouse_v_610, int greenhouse_pnr,
int p_greenhouse_c2, int p_greenhouse_c1,
Greenhouse_controller__greenhouse_controller_greenhouse_c1_out* _out);

typedef struct Greenhouse_controller__greenhouse_controller_out {
  int greenhouse_c2;
  int greenhouse_c1;
} Greenhouse_controller__greenhouse_controller_out;

void Greenhouse_controller__greenhouse_controller_step(int greenhouse_v_281,
                                                       int greenhouse_v_282,
                                                       int greenhouse_v_285,
                                                       int greenhouse_v_286,
                                                       int greenhouse_v_289,
                                                       int greenhouse_v_290,
                                                       int greenhouse_v_293,
                                                       int greenhouse_v_294,
                                                       int greenhouse_v_295,
                                                       int greenhouse_v_300,
                                                       int greenhouse_v_301,
                                                       int greenhouse_v_303,
                                                       int greenhouse_v_304,
                                                       int greenhouse_v_306,
                                                       int greenhouse_v_307,
                                                       int greenhouse_v_309,
                                                       int greenhouse_v_310,
                                                       int greenhouse_v_317,
                                                       int greenhouse_v_322,
                                                       int greenhouse_v_328,
                                                       int greenhouse_v_334,
                                                       int greenhouse_v_340,
                                                       int greenhouse_v_346,
                                                       int greenhouse_v_352,
                                                       int greenhouse_v_354,
                                                       int greenhouse_v_359,
                                                       int greenhouse_v_361,
                                                       int greenhouse_v_367,
                                                       int greenhouse_v_369,
                                                       int greenhouse_v_375,
                                                       int greenhouse_v_377,
                                                       int greenhouse_v_383,
                                                       int greenhouse_v_385,
                                                       int greenhouse_v_391,
                                                       int greenhouse_v_393,
                                                       int greenhouse_v_401,
                                                       int greenhouse_v_406,
                                                       int greenhouse_v_412,
                                                       int greenhouse_v_418,
                                                       int greenhouse_v_424,
                                                       int greenhouse_v_430,
                                                       int greenhouse_v_436,
                                                       int greenhouse_v_438,
                                                       int greenhouse_v_443,
                                                       int greenhouse_v_445,
                                                       int greenhouse_v_451,
                                                       int greenhouse_v_453,
                                                       int greenhouse_v_459,
                                                       int greenhouse_v_461,
                                                       int greenhouse_v_467,
                                                       int greenhouse_v_469,
                                                       int greenhouse_v_475,
                                                       int greenhouse_v_477,
                                                       int greenhouse_v_485,
                                                       int greenhouse_v_490,
                                                       int greenhouse_v_496,
                                                       int greenhouse_v_502,
                                                       int greenhouse_v_508,
                                                       int greenhouse_v_514,
                                                       int greenhouse_v_520,
                                                       int greenhouse_v_525,
                                                       int greenhouse_v_531,
                                                       int greenhouse_v_537,
                                                       int greenhouse_v_543,
                                                       int greenhouse_v_549,
                                                       int greenhouse_ck_1,
                                                       int greenhouse_pnr_4,
                                                       int greenhouse_ck_7_1,
                                                       int greenhouse_pnr_3,
                                                       int greenhouse_v_643,
                                                       int greenhouse_v_642,
                                                       int greenhouse_pnr_2,
                                                       int greenhouse_v_627,
                                                       int greenhouse_v_626,
                                                       int greenhouse_pnr_1,
                                                       int greenhouse_v_611,
                                                       int greenhouse_v_610,
                                                       int greenhouse_pnr,
                                                       int p_greenhouse_c2,
                                                       int p_greenhouse_c1,
                                                       Greenhouse_controller__greenhouse_controller_out* _out);

#endif // GREENHOUSE_CONTROLLER_H
